'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


fibonacci_sequence = [0, 1]
acc = 0
while True:
  length = len(fibonacci_sequence)
  index_n_1 = length - 2
  index_n_2 = length - 1
  next_term = fibonacci_sequence[index_n_1] + fibonacci_sequence[index_n_2]
  if next_term > 4000000:
    break
  fibonacci_sequence.append(next_term)

for ind in range(0, len(fibonacci_sequence), 1):
  if fibonacci_sequence[ind] % 2 == 0:
    acc += fibonacci_sequence[ind]

print (acc)